# actuator 应用监控端点配置
#management:
#  endpoints:
#    enabled-by-default: true
#  endpoint:
#    beans:
#      enabled: true
management:
  endpoints:
    web:
      exposure:
        # 开启refresh端点(刷新配置项)
        include: refresh
#        include: "*"