server:
  port: 8290
  servlet:
    context-path: /member
spring:
  application:
    name: member-service
  cloud:
    nacos:
      server-addr: 192.168.56.20:8848
      discovery:
        cluster-name: guangdong

nacos:
  config:
    server-addr: 192.168.56.20:8848
    username: nacos
    password: nacos